# Generated by Django 3.1.2 on 2020-11-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_accept', models.DateTimeField(null=True)),
                ('date_closed', models.DateTimeField(null=True)),
            ],
        ),
    ]
