# Generated by Django 3.1.2 on 2020-11-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested',
            name='star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requested',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requested',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
