# Generated by Django 3.1.2 on 2020-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20201127_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested',
            name='category',
            field=models.CharField(choices=[('Có chi phí', 'Có chi phí'), ('Bảo mật', 'Bảo mật'), ('Khác', 'Khác')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requested',
            name='star',
            field=models.CharField(choices=[('5 sao', '5 sao'), ('4 sao', '4 sao'), ('3 sao', '3 sao'), ('2 sao', '2 sao'), ('1 sao', '1 sao')], max_length=200, null=True),
        ),
    ]
