# Generated by Django 3.1.2 on 2020-11-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20201127_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='part',
            field=models.CharField(choices=[('Nhân sự', 'Nhân sự'), ('Kế toán', 'Kế toán'), ('XNK', 'XNK'), ('Kho', 'Kho'), ('Thu mua', 'Thu mua')], max_length=200, null=True),
        ),
    ]
