# Generated by Django 3.1.2 on 2020-11-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_quanly_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested',
            name='nhanvien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.nhanvien'),
        ),
    ]
