# Generated by Django 3.1.2 on 2020-11-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20201128_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requested',
            name='file',
        ),
    ]
