# Generated by Django 3.1.2 on 2020-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_remove_requested_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
