# Generated by Django 3.1.2 on 2020-12-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_requested_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Nhân sự', 'Nhân sự'), ('Kế toán', 'Kế toán'), ('XNK', 'XNK'), ('Kho', 'Kho'), ('Thu mua', 'Thu mua')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='part',
        ),
        migrations.RemoveField(
            model_name='quanly',
            name='part',
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.part'),
        ),
        migrations.AddField(
            model_name='quanly',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.part'),
        ),
        migrations.AddField(
            model_name='requested',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.part'),
        ),
    ]
