# Generated by Django 3.1.2 on 2020-12-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_auto_20201205_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requested',
            name='name',
        ),
    ]
