# Generated by Django 3.1.2 on 2020-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_remove_requested_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
